# Generated by Django 5.2.8 on 2025-11-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kulup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Kulüp Adı')),
                ('sehir', models.CharField(max_length=50, verbose_name='Şehir')),
                ('kurulus_yili', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kuruluş Yılı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='kulupler/', verbose_name='Kulüp Logosu')),
            ],
            options={
                'verbose_name_plural': 'Kulüpler',
            },
        ),
        migrations.CreateModel(
            name='Menajer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Menajer Adı Soyadı')),
                ('sirket_adi', models.CharField(blank=True, max_length=100, verbose_name='Şirket Adı')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='İletişim')),
            ],
            options={
                'verbose_name_plural': 'Menajerler',
            },
        ),
        migrations.CreateModel(
            name='Sporcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('dogum_tarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('boy', models.PositiveIntegerField(help_text='Santimetre cinsinden (Örn: 190)', verbose_name='Boy (cm)')),
                ('mevki', models.CharField(choices=[('PASOR', 'Pasör'), ('PASOR_CAPRAZI', 'Pasör Çaprazı'), ('SMACOR', 'Smaçör'), ('ORTA_OYUNCU', 'Orta Oyuncu'), ('LIBERO', 'Libero')], max_length=20, verbose_name='Mevki')),
                ('smac_yuksekligi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Smaç Yüksekliği (cm)')),
                ('blok_yuksekligi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Blok Yüksekliği (cm)')),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='sporcular/')),
                ('video_linki', models.URLField(blank=True, verbose_name='YouTube Video Linki')),
                ('kulup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oyuncular', to='core.kulup', verbose_name='Mevcut Kulübü')),
                ('menajer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.menajer', verbose_name='Menajeri')),
            ],
            options={
                'verbose_name_plural': 'Sporcular',
            },
        ),
    ]
