# Generated by Django 5.2.8 on 2025-11-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='blok_yuksekligi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Blok'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='boy',
            field=models.PositiveIntegerField(help_text='cm', verbose_name='Boy'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='smac_yuksekligi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Smaç'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='video_linki',
            field=models.URLField(blank=True, verbose_name='YouTube Linki'),
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(verbose_name='Maç Tarihi ve Saati')),
                ('skor', models.CharField(blank=True, default='-', help_text='Örn: 3-1', max_length=10, verbose_name='Skor')),
                ('deplasman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_maclari', to='core.kulup', verbose_name='Deplasman')),
                ('ev_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_maclari', to='core.kulup', verbose_name='Ev Sahibi')),
            ],
            options={
                'verbose_name_plural': 'Fikstür / Maçlar',
                'ordering': ['tarih'],
            },
        ),
        migrations.CreateModel(
            name='PuanDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oynanan', models.PositiveIntegerField(default=0, verbose_name='O')),
                ('galibiyet', models.PositiveIntegerField(default=0, verbose_name='G')),
                ('maglubiyet', models.PositiveIntegerField(default=0, verbose_name='M')),
                ('puan', models.PositiveIntegerField(default=0, verbose_name='P')),
                ('kulup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.kulup', verbose_name='Kulüp')),
            ],
            options={
                'verbose_name_plural': 'Puan Durumu',
                'ordering': ['-puan', '-galibiyet'],
            },
        ),
    ]
