# Generated by Django 5.2.8 on 2025-11-23 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sporcu_blok_yuksekligi_alter_sporcu_boy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mac',
            options={'ordering': ['tarih']},
        ),
        migrations.AlterModelOptions(
            name='puandurumu',
            options={'ordering': ['-puan', '-galibiyet']},
        ),
        migrations.AddField(
            model_name='menajer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='deplasman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_maclari', to='core.kulup'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='ev_sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_maclari', to='core.kulup'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='skor',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='mac',
            name='tarih',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='puandurumu',
            name='galibiyet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puandurumu',
            name='maglubiyet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puandurumu',
            name='oynanan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puandurumu',
            name='puan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='boy',
            field=models.PositiveIntegerField(blank=True, help_text='cm', null=True, verbose_name='Boy'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='mevki',
            field=models.CharField(blank=True, choices=[('PASOR', 'Pasör'), ('PASOR_CAPRAZI', 'Pasör Çaprazı'), ('SMACOR', 'Smaçör'), ('ORTA_OYUNCU', 'Orta Oyuncu'), ('LIBERO', 'Libero')], max_length=20, null=True, verbose_name='Mevki'),
        ),
    ]
