# Generated by Django 5.2.8 on 2025-11-23 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mac_options_alter_puandurumu_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menajer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sporcu',
            options={},
        ),
        migrations.AddField(
            model_name='sporcu',
            name='piyasa_degeri',
            field=models.PositiveIntegerField(blank=True, help_text='Sadece sayı girin (Örn: 50000)', null=True, verbose_name='Piyasa Değeri (€)'),
        ),
        migrations.AlterField(
            model_name='menajer',
            name='isim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menajer',
            name='sirket_adi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menajer',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='menajer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puandurumu',
            name='kulup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.kulup'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='blok_yuksekligi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='boy',
            field=models.PositiveIntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='isim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='kulup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oyuncular', to='core.kulup'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='menajer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.menajer'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='mevki',
            field=models.CharField(blank=True, choices=[('PASOR', 'Pasör'), ('PASOR_CAPRAZI', 'Pasör Çaprazı'), ('SMACOR', 'Smaçör'), ('ORTA_OYUNCU', 'Orta Oyuncu'), ('LIBERO', 'Libero')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='smac_yuksekligi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='video_linki',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezon', models.CharField(help_text='Örn: 2023-2024', max_length=20, verbose_name='Sezon')),
                ('tarih', models.DateField(blank=True, null=True)),
                ('tip', models.CharField(choices=[('Kiralık', 'Kiralık'), ('Bonservis', 'Bonservis'), ('Bedelsiz', 'Bedelsiz')], default='Bedelsiz', max_length=50)),
                ('eski_kulup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giden_transferler', to='core.kulup', verbose_name='Eski Kulüp')),
                ('sporcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferler', to='core.sporcu')),
                ('yeni_kulup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelen_transferler', to='core.kulup', verbose_name='Yeni Kulüp')),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
    ]
