# Generated by Django 5.2.8 on 2025-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_menajer_options_alter_sporcu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-sezon', '-id']},
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='piyasa_degeri',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Piyasa Değeri (€)'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sezon',
            field=models.CharField(max_length=20, verbose_name='Sezon'),
        ),
    ]
