# Generated by Django 5.2.8 on 2025-11-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transfer_options_alter_sporcu_piyasa_degeri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Haber Başlığı')),
                ('ozet', models.TextField(max_length=500, verbose_name='Kısa Özet')),
                ('icerik', models.TextField(verbose_name='Haber İçeriği')),
                ('resim', models.ImageField(upload_to='haberler/', verbose_name='Kapak Resmi')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.CharField(choices=[('Transfer', 'Transfer'), ('Mac', 'Maç Sonucu'), ('Ozel', 'Özel Haber')], default='Ozel', max_length=20)),
                ('manset_mi', models.BooleanField(default=False, verbose_name='Manşette Göster')),
            ],
            options={
                'verbose_name_plural': 'Haberler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.AlterField(
            model_name='transfer',
            name='eski_kulup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giden_transferler', to='core.kulup'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='yeni_kulup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelen_transferler', to='core.kulup'),
        ),
    ]
