# Generated by Django 5.2.8 on 2025-11-23 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_haber_alter_transfer_eski_kulup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(max_length=200)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='haber',
            options={'ordering': ['-tarih']},
        ),
        migrations.AlterModelOptions(
            name='kulup',
            options={},
        ),
        migrations.AddField(
            model_name='sporcu',
            name='begeniler',
            field=models.ManyToManyField(blank=True, related_name='begendigi_sporcular', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='haber',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='haber',
            name='icerik',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='haber',
            name='manset_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='haber',
            name='ozet',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='haber',
            name='resim',
            field=models.ImageField(upload_to='haberler/'),
        ),
        migrations.AlterField(
            model_name='kulup',
            name='isim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kulup',
            name='kurulus_yili',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kulup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='kulupler/'),
        ),
        migrations.AlterField(
            model_name='kulup',
            name='sehir',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mac',
            name='deplasman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='core.kulup'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='ev_sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev', to='core.kulup'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='boy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='piyasa_degeri',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='eski_kulup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giden', to='core.kulup'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sezon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='tip',
            field=models.CharField(default='Bedelsiz', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='yeni_kulup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelen', to='core.kulup'),
        ),
        migrations.CreateModel(
            name='Secenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(max_length=200)),
                ('oy_sayisi', models.PositiveIntegerField(default=0)),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='core.anket')),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField(verbose_name='Yorumunuz')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('haber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='core.haber')),
                ('sporcu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='core.sporcu')),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
    ]
