# Generated by Django 5.2.8 on 2025-11-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_anket_alter_haber_options_alter_kulup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mac',
            options={'ordering': ['tarih'], 'verbose_name_plural': 'Fikstür / Maçlar'},
        ),
        migrations.AddField(
            model_name='mac',
            name='hakemler',
            field=models.CharField(blank=True, help_text='Örn: Nurper Özbar, Erol Akbulut', max_length=200, verbose_name='Hakemler'),
        ),
        migrations.AddField(
            model_name='mac',
            name='salon',
            field=models.CharField(blank=True, help_text='Örn: Burhan Felek', max_length=100, verbose_name='Salon Adı'),
        ),
        migrations.AddField(
            model_name='mac',
            name='set1',
            field=models.CharField(blank=True, help_text='25-18', max_length=10, verbose_name='1. Set'),
        ),
        migrations.AddField(
            model_name='mac',
            name='set2',
            field=models.CharField(blank=True, help_text='22-25', max_length=10, verbose_name='2. Set'),
        ),
        migrations.AddField(
            model_name='mac',
            name='set3',
            field=models.CharField(blank=True, help_text='25-15', max_length=10, verbose_name='3. Set'),
        ),
        migrations.AddField(
            model_name='mac',
            name='set4',
            field=models.CharField(blank=True, max_length=10, verbose_name='4. Set'),
        ),
        migrations.AddField(
            model_name='mac',
            name='set5',
            field=models.CharField(blank=True, max_length=10, verbose_name='5. Set'),
        ),
        migrations.AddField(
            model_name='mac',
            name='tamamlandi',
            field=models.BooleanField(default=False, verbose_name='Maç Bitti'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='deplasman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_maclari', to='core.kulup', verbose_name='Deplasman'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='ev_sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_maclari', to='core.kulup', verbose_name='Ev Sahibi'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='skor',
            field=models.CharField(blank=True, default='-', help_text='Örn: 3-1', max_length=10, verbose_name='Maç Skoru'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='tarih',
            field=models.DateTimeField(verbose_name='Tarih ve Saat'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='metin',
            field=models.TextField(),
        ),
    ]
