# Generated by Django 5.2.8 on 2025-11-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mac_options_mac_hakemler_mac_salon_mac_set1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tahmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.CharField(choices=[('3-0', '3-0'), ('3-1', '3-1'), ('3-2', '3-2'), ('0-3', '0-3'), ('1-3', '1-3'), ('2-3', '2-3')], max_length=5)),
                ('puan_kazandi', models.IntegerField(default=0, help_text='Maç bitince hesaplanır')),
                ('hesaplandi', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahminler', to='core.mac')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahminler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mac')},
            },
        ),
    ]
